spring:
  application:
    name: eureka-serivce

server:
  port: 8089

eureka:
  instance:
    hostname: service2
  client:
    service-url:
      defaultZone: http://service1:8088/eureka/
  server:
    enable-self-preservation: false
